
package ee.jaxws.example;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldExample", targetNamespace = "http://example.jaxws.ee/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldExample {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://example.jaxws.ee/", className = "ee.jaxws.example.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://example.jaxws.ee/", className = "ee.jaxws.example.SayHelloResponse")
    @Action(input = "http://example.jaxws.ee/HelloWorldExample/sayHelloRequest", output = "http://example.jaxws.ee/HelloWorldExample/sayHelloResponse")
    public String sayHello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
