
package ee.jaxws.example;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloWorldExampleImplService", targetNamespace = "http://example.jaxws.ee/", wsdlLocation = "http://localhost:8080/sayHelloWorld?wsdl")
public class HelloWorldExampleImplService
    extends Service
{

    private final static URL HELLOWORLDEXAMPLEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOWORLDEXAMPLEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOWORLDEXAMPLEIMPLSERVICE_QNAME = new QName("http://example.jaxws.ee/", "HelloWorldExampleImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sayHelloWorld?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOWORLDEXAMPLEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOWORLDEXAMPLEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloWorldExampleImplService() {
        super(__getWsdlLocation(), HELLOWORLDEXAMPLEIMPLSERVICE_QNAME);
    }

    public HelloWorldExampleImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOWORLDEXAMPLEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldExampleImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOWORLDEXAMPLEIMPLSERVICE_QNAME);
    }

    public HelloWorldExampleImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOWORLDEXAMPLEIMPLSERVICE_QNAME, features);
    }

    public HelloWorldExampleImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldExampleImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloWorldExample
     */
    @WebEndpoint(name = "HelloWorldExampleImplPort")
    public HelloWorldExample getHelloWorldExampleImplPort() {
        return super.getPort(new QName("http://example.jaxws.ee/", "HelloWorldExampleImplPort"), HelloWorldExample.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldExample
     */
    @WebEndpoint(name = "HelloWorldExampleImplPort")
    public HelloWorldExample getHelloWorldExampleImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.jaxws.ee/", "HelloWorldExampleImplPort"), HelloWorldExample.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOWORLDEXAMPLEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOWORLDEXAMPLEIMPLSERVICE_EXCEPTION;
        }
        return HELLOWORLDEXAMPLEIMPLSERVICE_WSDL_LOCATION;
    }

}
